# Практика №2
## Робота з NumPy


In [2]:
import numpy as np

1. Створіть вектор (1,2,3) і виведіть його. Виведіть тип масиву.
2. Створіть наступну матрицю і виведіть її:
$$
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right)
$$ 
3. Створіть нульову матрицю розміром (4,5) - див. numpy.zeros.
4. Створіть одиничну матрицю розміром (3,3) - див. numpy.identity.
5. Виведіть розмір матриці, створеної на 2 кроці.
6. Створити дві матриці  $A = 
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6
\end{array}\right)
$ і $B = 
\left(\begin{array}{cc} 
-1 & -2 & -3\\
-4 & -5 & -6
\end{array}\right)
$. Виконайте операції додавання і віднімання для цих двох матриць.
7. Для вищезазначених матриць виконайте поелементне множення.
8. До матриці $A$ додайте константу $b=2$.
9. Виконайте множення матриці $\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6
\end{array}\right)
$ на матрицю $\left(\begin{array}{cc} 
1 & 1\\
1 & 1\\
1 & 1
\end{array}\right)
$
10. Для двох векторів $v = (1,2,3)$ і $u = (1,1,1)$ знайти Евклідову норму (див. numpy.linalg.norm)
11. Дано вектор $[11,22,33,44,55]$. Необхідно вивести усі елементи від передостаннього елемента до кінця (використайте зріз).


In [3]:
# 1. Створити вектор і вивести його
vector = np.array([1, 2, 3])
print("Вектор:", vector)
print("Тип масиву:", type(vector))

# 2. Створити матрицю і вивести її
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Матриця:")
print(matrix)

# 3. Створити нульову матрицю
zero_matrix = np.zeros((4, 5))
print("Нульова матриця:")
print(zero_matrix)

# 4. Створити одиничну матрицю
identity_matrix = np.identity(3)
print("Одинична матриця:")
print(identity_matrix)

# 5. Вивести розмір матриці
matrix_shape = matrix.shape
print("Розмір матриці:", matrix_shape)

# 6. Виконати операції додавання і віднімання матриць
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[-1, -2, -3], [-4, -5, -6]])

addition = A + B
subtraction = A - B

print("Додавання матриць:")
print(addition)
print("Віднімання матриць:")
print(subtraction)

# 7. Виконати поелементне множення
elementwise_multiplication = A * B
print("Поелементне множення:")
print(elementwise_multiplication)

# 8. Додати константу до матриці
b = 2
result = A + b
print("Матриця після додавання константи:")
print(result)

# 9. Виконати множення матриць
C = np.array([[1, 2, 3], [4, 5, 6]])
D = np.array([[1, 1], [1, 1], [1, 1]])

matrix_multiplication = np.dot(C, D)
print("Множення матриць:")
print(matrix_multiplication)

# 10. Знайти Евклідову норму векторів
v = np.array([1, 2, 3])
u = np.array([1, 1, 1])

v_norm = np.linalg.norm(v)
u_norm = np.linalg.norm(u)

print("Евклідова норма вектора v:", v_norm)
print("Евклідова норма вектора u:", u_norm)

# 11. Вивести елементи від передостаннього до кінця
vector = np.array([11, 22, 33, 44, 55])
result = vector[-2:]
print("Елементи від передостаннього до кінця:")
print(result)


Вектор: [1 2 3]
Тип масиву: <class 'numpy.ndarray'>
Матриця:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Нульова матриця:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Одинична матриця:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Розмір матриці: (3, 3)
Додавання матриць:
[[0 0 0]
 [0 0 0]]
Віднімання матриць:
[[ 2  4  6]
 [ 8 10 12]]
Поелементне множення:
[[ -1  -4  -9]
 [-16 -25 -36]]
Матриця після додавання константи:
[[3 4 5]
 [6 7 8]]
Множення матриць:
[[ 6  6]
 [15 15]]
Евклідова норма вектора v: 3.7416573867739413
Евклідова норма вектора u: 1.7320508075688772
Елементи від передостаннього до кінця:
[44 55]
